import type { StripeWebhookHandler } from '@payloadcms/plugin-stripe/types'
import type Stripe from 'stripe'

export const paymentIntentSucceeded: StripeWebhookHandler<{
  data: { object: Stripe.PaymentIntent }
}> = async ({ event, payload }) => {
  const paymentIntent = event.data.object
  const cartId = paymentIntent.metadata?.cartId

  if (!cartId) {
    payload.logger.error('PaymentIntent missing cartId in metadata')
    return
  }

  payload.logger.info(`Processing payment_intent.succeeded for cart ${cartId}`)

  try {
    // Check if order already exists (idempotency)
    const existingOrders = await payload.find({
      collection: 'orders',
      where: {
        stripePaymentIntentId: { equals: paymentIntent.id },
      },
      limit: 1,
    })

    if (existingOrders.docs.length > 0) {
      payload.logger.info(`Order already exists for payment ${paymentIntent.id}`)
      return
    }

    // Retrieve cart with full depth
    const cart = await payload.findByID({
      collection: 'carts',
      id: cartId,
      depth: 2,
    })

    if (!cart) {
      payload.logger.error(`Cart ${cartId} not found`)
      return
    }

    if (cart.completedAt) {
      payload.logger.info(`Cart ${cartId} already completed`)
      return
    }

    // Get shipping option details
    let shippingMethod = { name: 'Standard', amount: 0 }
    if (cart.shippingOption) {
      const shippingOptionId =
        typeof cart.shippingOption === 'object' && cart.shippingOption !== null
          ? String(cart.shippingOption.id)
          : String(cart.shippingOption)
      try {
        const shippingOption = await payload.findByID({
          collection: 'shipping',
          id: shippingOptionId,
        })
        if (shippingOption) {
          shippingMethod = { name: shippingOption.name, amount: shippingOption.amount }
        }
      } catch {
        payload.logger.warn(`Could not retrieve shipping option ${shippingOptionId}`)
      }
    }

    // Build order items
    const orderItems = (cart.items || [])
      .filter((item: any) => item && item.product)
      .map((item: any) => {
        const isPopulated = typeof item.product === 'object' && item.product !== null
        const productId = isPopulated ? String(item.product.id) : String(item.product)
        return {
          productId,
          productTitle: isPopulated ? item.product.title || 'Product' : 'Product',
          productDescription: isPopulated ? item.product.description || '' : '',
          thumbnail: isPopulated ? item.product.thumbnail?.url || '' : '',
          quantity: item.quantity || 1,
          unitPrice: item.unitPrice || 0,
        }
      })
      .filter(
        (item: any) =>
          item.productId &&
          item.productId !== 'null' &&
          item.productId !== 'undefined' &&
          item.productId !== '',
      )

    // Create order
    const order = await payload.create({
      collection: 'orders',
      data: {
        displayId: '', // Auto-generated by hook
        email: cart.email || '',
        items: orderItems,
        shippingAddress: cart.shippingAddress as any,
        shippingMethod,
        subtotal: cart.subtotal || 0,
        shippingTotal: cart.shippingTotal || 0,
        total: cart.total || 0,
        stripePaymentIntentId: paymentIntent.id,
        status: 'confirmed',
      },
    })

    payload.logger.info(`Created order ${order.displayId} from webhook`)

    // Mark products as unavailable
    for (const item of cart.items || []) {
      const productId =
        typeof item.product === 'object' && item.product !== null
          ? String(item.product.id)
          : String(item.product)
      try {
        await payload.update({
          collection: 'products',
          id: productId,
          data: { available: false },
        })
      } catch {
        payload.logger.warn(`Could not mark product ${productId} as unavailable`)
      }
    }

    // Mark cart as completed
    await payload.update({
      collection: 'carts',
      id: cartId,
      data: {
        completedAt: new Date().toISOString(),
        paymentStatus: 'succeeded',
      },
    })

    payload.logger.info(`Webhook processing complete for cart ${cartId}`)
  } catch (error) {
    payload.logger.error(`Error processing payment webhook: ${error}`)
    throw error // Re-throw to signal webhook failure to Stripe
  }
}
