import { NextRequest, NextResponse } from 'next/server'
import { getPayloadClient } from '@/lib/payload'
import Stripe from 'stripe'

const getStripe = () => new Stripe(process.env.STRIPE_API_KEY!, {
  apiVersion: '2025-02-24.acacia',
})

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  try {
    const { id } = await params
    const payload = await getPayloadClient()

    const cart = await payload.findByID({
      collection: 'carts',
      id,
      depth: 2,
    })

    if (!cart.stripePaymentIntentId) {
      return NextResponse.json({ error: 'No payment intent found', type: 'cart' }, { status: 400 })
    }

    // Verify payment with Stripe
    const paymentIntent = await getStripe().paymentIntents.retrieve(cart.stripePaymentIntentId)

    if (paymentIntent.status !== 'succeeded') {
      return NextResponse.json(
        { error: 'Payment not completed', type: 'cart' },
        { status: 400 },
      )
    }

    // Get shipping option details
    let shippingMethod = { name: 'Standard', amount: 0 }
    if (cart.shippingOption) {
      const shippingOptionId =
        typeof cart.shippingOption === 'string' || typeof cart.shippingOption === 'number'
          ? String(cart.shippingOption)
          : cart.shippingOption.id
      const shippingOption = await payload.findByID({
        collection: 'shipping',
        id: shippingOptionId,
      })
      if (shippingOption) {
        shippingMethod = { name: shippingOption.name, amount: shippingOption.amount }
      }
    }

    // Create order from cart
    const order = await payload.create({
      collection: 'orders',
      data: {
        displayId: '', // Will be auto-generated by hook
        email: cart.email || '',
        items: (cart.items || []).map((item: any) => ({
          productId: typeof item.product === 'string' ? item.product : item.product.id,
          productTitle: typeof item.product === 'string' ? 'Product' : item.product.title,
          productDescription:
            typeof item.product === 'string' ? '' : item.product.description || '',
          thumbnail:
            typeof item.product === 'string'
              ? ''
              : item.product.thumbnail?.url || '',
          quantity: item.quantity,
          unitPrice: item.unitPrice,
        })),
        shippingAddress: cart.shippingAddress as any,
        shippingMethod,
        subtotal: cart.subtotal || 0,
        shippingTotal: cart.shippingTotal || 0,
        total: cart.total || 0,
        stripePaymentIntentId: cart.stripePaymentIntentId || undefined,
        status: 'confirmed',
      },
    })

    // Mark sold products as unavailable
    for (const item of cart.items || []) {
      const productId =
        typeof item.product === 'string' || typeof item.product === 'number'
          ? String(item.product)
          : item.product.id
      await payload.update({
        collection: 'products',
        id: productId,
        data: { available: false },
      })
    }

    // Mark cart as completed
    await payload.update({
      collection: 'carts',
      id,
      data: { completedAt: new Date().toISOString() },
    })

    return NextResponse.json({ type: 'order', order })
  } catch (error) {
    console.error('Error completing cart:', error)
    return NextResponse.json({ error: 'Failed to complete order' }, { status: 500 })
  }
}
